CREATE TABLE CLIENTES 
(
  NUMERODOCUMENTO NUMBER NOT NULL 
, TIPODOCUMENTO VARCHAR2(20 BYTE) NOT NULL 
, NOMBRE VARCHAR2(20 BYTE) NOT NULL 
, NACIONALIDAD VARCHAR2(30 BYTE) NOT NULL 
, DIRECCIONFISICA VARCHAR2(30 BYTE) NOT NULL 
, DIRECCIONELECTRONICA VARCHAR2(30 BYTE) NOT NULL 
, TELEFONO VARCHAR2(20 BYTE) NOT NULL 
, CIUDAD VARCHAR2(20 BYTE) NOT NULL 
, DEPARTAMENTO VARCHAR2(20 BYTE) NOT NULL 
, CODIGOPOSTAL NUMBER NOT NULL 
, PASSWORD VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT CLIENTES_PK PRIMARY KEY 
  (
    NUMERODOCUMENTO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
