CREATE TABLE CUENTAS 
(
  NUMCUENTA NUMBER NOT NULL 
, TIPOCUENTA VARCHAR2(20 BYTE) NOT NULL 
, SALDO LONG NOT NULL 
, ESTADO VARCHAR2(20 BYTE) NOT NULL 
, FECHAULTIMATRANSACCION DATE NOT NULL 
, NUMDOCCLIENTE NUMBER NOT NULL 
, FECHACREACION DATE NOT NULL 
, IDOFICINA NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE UNIQUE INDEX CUENTAS_PK ON CUENTAS (NUMCUENTA ASC) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
