CREATE TABLE OFICINAS 
(
  NOMBRE VARCHAR2(20 BYTE) NOT NULL 
, DIRECCION VARCHAR2(20 BYTE) NOT NULL 
, NUMPUNTOSATENCION VARCHAR2(20 BYTE) 
, ID NUMBER NOT NULL 
, NUMDOCGERENTE NUMBER NOT NULL 
, CONSTRAINT OFICINAS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE OFICINAS
ADD CONSTRAINT OFICINAS_FK1 FOREIGN KEY
(
  NUMDOCGERENTE 
)
REFERENCES EMPLEADOS
(
  )
ENABLE;
