CREATE TABLE OPERACIONESCUENTAS 
(
  TIPOOPERACION VARCHAR2(20 BYTE) NOT NULL 
, IDPUNTOATENCION NUMBER NOT NULL 
, VALOR VARCHAR2(20 BYTE) NOT NULL 
, NUMCUENTA NUMBER NOT NULL 
, ID VARCHAR2(20 BYTE) NOT NULL 
, FECHA VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT OPERACIONESCUENTAS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE OPERACIONESCUENTAS
ADD CONSTRAINT OPERACIONESCUENTAS_FK1 FOREIGN KEY
(
  NUMCUENTA 
)
REFERENCES CUENTAS
(
  )
ENABLE;

ALTER TABLE OPERACIONESCUENTAS
ADD CONSTRAINT OPERACIONESCUENTAS_FK2 FOREIGN KEY
(
  IDPUNTOATENCION 
)
REFERENCES PUNTOSATENCION
(
  )
ENABLE;
