CREATE TABLE OPERACIONESTRANSFERENCIA 
(
  ID NUMBER NOT NULL 
, NUMCUENTADESTINO NUMBER NOT NULL 
, VALOR NUMBER NOT NULL 
, IDPUNTOATENCION NUMBER NOT NULL 
, FECHA DATE NOT NULL 
, NUMCUENTAORIGEN NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
