CREATE TABLE OPERACIONESPRESTAMO 
(
  ID NUMBER NOT NULL 
, TIPOOPERACION VARCHAR2(20 BYTE) NOT NULL 
, VALOR NUMBER NOT NULL 
, FECHA DATE NOT NULL 
, IDPUNTOATENCION NUMBER NOT NULL 
, NUMPRESTAMO NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
