CREATE TABLE PRESTAMOS 
(
  NUMPRESTAMO NUMBER NOT NULL 
, MONTO NUMBER NOT NULL 
, INTERESES NUMBER NOT NULL 
, ESTADO VARCHAR2(20 BYTE) NOT NULL 
, NUMCUOTAS NUMBER NOT NULL 
, TIPOPRESTAMO VARCHAR2(20 BYTE) NOT NULL 
, DIAPAGOPROXIMACUOTA DATE NOT NULL 
, NUMDOCCLIENTE NUMBER NOT NULL 
, CONSTRAINT PRESTAMOS_PK PRIMARY KEY 
  (
    NUMPRESTAMO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE PRESTAMOS
ADD CONSTRAINT PRESTAMOS_FK1 FOREIGN KEY
(
  NUMDOCCLIENTE 
)
REFERENCES CLIENTES
(
  )
ENABLE;
